### ISSUE TITLE
Support primary language and topics of Repo

### ISSUE THREAD

**Issue by imfycc** [lcjnil/github-notion-star#4]
Can I add two more columns to the notion database?

Including primary language and topics of Repo

I’d be happy to contribute the code, if that’s okay.

**Comment by lcjnil** [comment]
You can add more columns at your wish(or remove current columns except first 5), this does not require any script modification.

**Comment by imfycc** [comment]
close #5

**Comment by imfycc** [comment]
@lcjnil  Notion of the template need to add these three fields.

https://github.com/lcjnil/github-notion-star/blob/main/libs/notion.ts#L114-L136

**Comment by lcjnil** [comment]
@imfycc Template is updated and I removed column `Updated At` at #6
